# Site settings
title: HKU PL Group
permalink: 'pretty'
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js', 'README.md']
# email: not yet set
description: > # this means to ignore newlines until "baseurl:"
  Programming Languages Group from The University of Hong Kong
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hkuplg.github.io" # the base hostname & protocol for your site
#twitter_username: hkuplg
github_username:  hkuplg
about: We are a group of programming language researchers who study topics about functional language design, type theory, compilers and program analysis.
location: The University of Hong Kong

# Build settings
timezone: Asia/Hong_Kong
markdown: kramdown
future : true # so that pages in the future get built; doesn't work :/
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

plugins: [jekyll-paginate]
paginate: 5
paginate_path: seminar/page:num/

projects_btn: "Gallery"
posts_btn: "Seminar"
close_btn: "Close"
members_btn: "Members"
highlight_btn: "Highlight"
